project/core/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from project import db
from project.models import Notebooks, Desks
from project.core.daynight import eval_time


core = Blueprint('core', __name__, template_folder = "templates/core")

@core.route('/')
def index():
    recent_notebooks = Notebooks.query.filter_by(visibility = "PUBLIC").order_by(Notebooks.last_update.desc()).limit(10)
    featured_table = Desks.query.filter_by(owner = 2).filter_by(deskname = "Featured").first()
    if featured_table is not None:
        featured_notebooks = Notebooks.query.filter(Notebooks.associated_desks.contains(featured_table))
    else:
        featured_notebooks = [Notebooks(title = "Featured desk is missing.", desc = "", creation_date = "", last_update = "", visibility = "PUBLIC", access_code = "", url = "", cover_img = "", owner = 1)]
    return render_template('index.html', webtitle = "Homepage", daynight = eval_time(), recent_notebooks = recent_notebooks, featured_notebooks = featured_notebooks)


@core.route('/search', methods=['GET'])
def search():
    if request.args.get('query'):
        search_term = request.args.get('query')
        search_results = Notebooks.query.filter_by(visibility = "PUBLIC").filter(Notebooks.title.contains(search_term))
        if search_results.count() == 0:
            search_results = 0

        # if current_user.is_authenticated:
        #     personal_results = Notebooks.query.filter_by(owner = current_user.id).filter(Notebooks.title.contains(search_term))
        #     if personal_results is None:
        #         personal_results = 0
        # else:
        #     personal_results = 0
    else:
        search_results = 0


    return render_template('search.html', webtitle = "Search", daynight = eval_time(), search_results = search_results)



@core.route('/info')
def info():
    info_table = Desks.query.filter_by(owner = 2).filter_by(deskname = "Info").first()
    if info_table is not None:
        info_notebooks = Notebooks.query.filter(Notebooks.associated_desks.contains(info_table))
    else:
        info_notebooks = [Notebooks(title = "Info desk is missing.", desc = "", creation_date = "", last_update = "", visibility = "PUBLIC", access_code = "", url = "", cover_img = "", owner = 1)]
    return render_template('about.html', webtitle = "About", daynight = eval_time(), info_notebooks = info_notebooks)

project/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from project import db, mail
from flask_mail import Message
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash
from project.core.daynight import eval_time
import time

#forms
from project.users.forms import login_form, registration_form, changePassword_form, report_form, preferences_form, profile_form, pw_reset_form, pw_reset_request_form, email_login_form

# #models
from project.models import Users, Desks, Reports, Preferences


accounts = Blueprint('users', __name__, template_folder = "templates/users")

@accounts.route('/login', methods=['POST', 'GET'])
def login():
    form = login_form()
    if form.validate_on_submit():
        this_user = Users.query.filter_by(username = form.username.data.lower()).first()
        if this_user is not None and this_user.check_password(form.password.data):
            login_user(this_user)
            flash('Logged In')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('desks.index')
            return redirect(next)
        else:
            flash('You have provided a wrong username or password.')
            return redirect(url_for('users.login'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('login.html', webtitle = "Log In", daynight = eval_time(), form = form)


@accounts.route('/email_login', methods=['POST', 'GET'])
def email_login():
    form = email_login_form()
    if form.validate_on_submit():
        this_user = Users.query.filter_by(email = form.email.data.lower()).first()
        if this_user is not None and this_user.check_password(form.password.data):
            login_user(this_user)
            flash('Logged In')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('desks.index')
            return redirect(next)
        else:
            flash('You have provided a wrong email or password.')
            return redirect(url_for('users.email_login'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('email_login.html', webtitle = "Log In", daynight = eval_time(), form = form)



@accounts.route('/signup', methods=['POST', 'GET'])
def register():
    form = registration_form()
    if form.validate_on_submit():
        new_user = Users(username = form.username.data.lower(), email = form.email.data, password = form.password.data, bio = "", pic = "https://www.fluidnotebook.com/static/images/defaultavatar.png", active_desk = 0)
        db.session.add(new_user)
        db.session.commit()
        new_desk = Desks(deskname = "Main Desk", desc = ("The primary desk that's setup for {}.".format(new_user.username)), owner = new_user.id)
        db.session.add(new_desk)
        db.session.commit()
        new_user.active_desk = new_desk.id
        user_prefs = Preferences(timezone = "Etc/GMT+8", night_on = 21, night_off = 7, night_type = "dark", font_size = "18", coding_addon = 0, hyperlinks_addon = 0, colors_addon = 0, user_id = new_user.id)
        db.session.add(user_prefs)
        db.session.commit()
        flash("Your account has been registered, please log in!")
        return redirect(url_for('users.login'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('register.html', webtitle = "Register an Account", daynight = eval_time(), form = form)


@accounts.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out.')
    return redirect(url_for('core.index'))


@accounts.route('/change_password', methods = ['GET', 'POST'])
@login_required
def change_password():
    this_user = Users.query.get(current_user.id)
    form = changePassword_form()
    if form.validate_on_submit():
        if this_user.check_password(form.current_pw.data):
            this_user.password = generate_password_hash(form.new_pw.data)
            db.session.commit()
            flash('Password Changed.')
            return redirect(url_for('users.settings'))
        else:
            print(generate_password_hash(form.current_pw.data))
            print(this_user.password)
            flash('Your current password is wrong, please try again.')
            return redirect(url_for('users.change_password'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('changepassword.html', webtitle = "Change Password", daynight = eval_time(), form = form)



@accounts.route('/report', methods = ['POST', 'GET'])
def report():
    form = report_form()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            reporter = current_user.username
        else:
            reporter = "unauthenticated"
        new_report = Reports(type = form.type.data, url = form.url.data, content = form.content.data, user = reporter, date = int(time.time()))
        db.session.add(new_report)
        db.session.commit()
        flash('Your report has been submitted, thank you!')
        return redirect(url_for('users.report'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('report.html', webtitle = "Report", daynight = eval_time(), form = form)



@accounts.route('/myinfo', methods = ['POST', 'GET'])
@login_required
def change_info():
    target_user = Users.query.get(current_user.id)
    form = profile_form(obj = target_user)
    if form.validate_on_submit():
        target_user.bio = form.bio.data
        target_user.email = form.email.data
        target_user.pic = form.pic.data
        db.session.commit()
        flash('Your details have been updated.')
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('myinfo.html', webtitle = "My Information", daynight = eval_time(), form = form)



@accounts.route('/settings', methods = ['POST', 'GET'])
@login_required
def settings():
    return render_template('settings.html', webtitle = "Settings", daynight = eval_time())



@accounts.route('/preferences', methods = ['GET', 'POST'])
@login_required
def preferences():
    user_prefs = Preferences.query.filter_by(user_id = current_user.id).first()
    form = preferences_form(obj = user_prefs)
    if form.validate_on_submit():
        user_prefs.timezone = form.timezone.data
        user_prefs.night_time_on = form.night_time_on.data
        user_prefs.night_time_off = form.night_time_off.data
        user_prefs.night_mode_type = form.night_mode_type.data
        user_prefs.font_size = form.font_size.data
        user_prefs.coding_addon = form.coding_addon.data
        user_prefs.hyperlinks_addon = form.hyperlinks_addon.data
        user_prefs.colors_addon = form.colors_addon.data
        db.session.commit()
        flash('Settings Updated.')
        return redirect(url_for('users.settings'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('preferences.html', webtitle = "Account Preferences", daynight = eval_time(), form = form)



@accounts.route('/device', methods = ['GET', 'POST'])
def device_settings():
    if "modified_settings" in request.form:
        if request.form['daynight_pref'] != "AUTO":
            session['daynight_pref'] = request.form['daynight_pref']
        elif request.form['daynight_pref'] == "AUTO" and session.get('daynight_pref'):
            session.pop('daynight_pref')

        if request.form['font_size_pref'] != "AUTO":
            session['font_size_pref'] = request.form['font_size_pref']
        session['keywords_pref'] = request.form['keywords_pref']

        if "editor_pref" in request.form:
            session['editor_pref'] = request.form['editor_pref']


    if request.args.get('clear'):
        if request.args.get('clear') == "session":
            if session.get('daynight_pref'):
                session.pop('daynight_pref')
            if session.get('font_size_pref'):
                session.pop('font_size_pref')
            if session.get('keywords_pref'):
                session.pop('keywords_pref')
            if session.get('editor_pref'):
                session.pop('editor_pref')

            flash('Your device-specific settings have been cleared.')

    return render_template('device_settings.html', webtitle = "Device-Specific Settings", daynight = eval_time())



@accounts.route('/forgot_password', methods = ['GET', 'POST'])
def forgot_password():
    if current_user.is_authenticated:
        flash("Actually, you're already logged in.")
        return redirect(url_for('core.index'))
    else:
        form = pw_reset_request_form()
        if form.validate_on_submit():
            target_user = Users.query.filter_by(email = form.email.data).first()
            token = target_user.get_reset_token()
            email_message = Message('Password Reset Request', sender = 'noreply@sensworks.ca', recipients = [target_user.email])
            email_message.body = f"""Hey {target_user.username}, \n
I heard that you forgot your password for your account at Fluid Notebook. Please click on the following link to reset it. \n
{url_for('users.reset_password', token = token, _external = True)}\n
This link will expire in 30 mins, please do not share it with anyone, as they'll be able to change your password.\n\n
Thanks for using Fluid Notebook!\n
Daryl"""
            mail.send(email_message)

project/templates/base.html
{% set version = "1.8.3B" %}
<!DOCTYPE html>
{% if current_user.is_authenticated %}
{% set css_file = current_user.preferences.night_mode_type %}
{% else %}
{% set css_file = "dark" %}
{% endif %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Fluid Notebook {% if webtitle %} - {{webtitle}}{% endif %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/fav.ico') }}">
    <style>
      body {
        {% if session['font_size_pref'] %}
          font-size: {{ session['font_size_pref'] }}px; /* device-specific */
        {% else %}
          {% if current_user.is_authenticated %}
            font-size: {{ current_user.preferences.font_size }}px; /* account settings */
          {% else %}
            font-size: 18px; /* default */
          {% endif %}
        {% endif %}
      }
    </style>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fluid-constant.css') }}?v={{version}}">
    {% if daynight == "NIGHT" %}
      <link rel="stylesheet" href="/static/css/fluid-{{css_file}}.css?v={{version}}">
    {% else %}
      <link rel="stylesheet" href="/static/css/fluid-day.css?v={{version}}">
    {% endif %}

    {% if session['editor_pref'] %}
      <link rel="stylesheet" href="/static/css/quill-{{session['editor_pref']}}.css?v={{version}}">
    {% else %}
      <link rel="stylesheet" href="/static/css/quill-snow.css?v={{version}}">
    {% endif %}

    <script src="{{ url_for('static', filename='js/toggles.js') }}?v={{version}}"></script>
    {% if session['keywords_pref'] %}
      {% if session['keywords_pref'] == "OFF" %}
      {% else %}
        <script type="text/javascript">
          var keymap = {};
          onkeydown = onkeyup = function(e){
              e = e || event; // to deal with IE
              keymap[e.keyCode] = e.type == 'keydown';
              if ((keymap[75]))
              {
                  document.getElementById("toggleKeywordsButton").click();
              }
          }
        </script>
      {% endif %}
    {% else %}
      <script type="text/javascript">
        var keymap = {};
        onkeydown = onkeyup = function(e){
            e = e || event; // to deal with IE
            keymap[e.keyCode] = e.type == 'keydown';
            if ((keymap[75]))
            {
                document.getElementById("toggleKeywordsButton").click();
            }
        }
      </script>
    {% endif %}
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  </head>
  <body>
    <header>
      <a href="/" id="webTitle_link"><div id="webTitle">
        Fluid
      </div></a>
      <nav id="horizontal">
        <a href="{{ url_for('desks.index') }}">Desk</a>
        <a href="{{ url_for('core.info') }}">Info</a>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('users.settings') }}">Account</a>
        <a href="{{ url_for('users.logout') }}">Logout</a>
        {% else %}
        <a href="{{ url_for('users.device_settings') }}">Settings</a>
        <a href="{{ url_for('users.login') }}">Login</a>
        {% endif %}
      </nav>
      <button id="floatingMenuButton" onClick="toggleMenu()">&#9776;</button>
      <div id="curtain" style="display: none;" onClick="toggleMenu()"></div>
      <nav id="mobile" style="width: 0;">
        <div id="mobileNavContainer">
          <a href="{{ url_for('desks.index') }}">Desk</a>
          <a href="{{ url_for('core.info') }}">Info</a>
          {% if current_user.is_authenticated %}
          <a href="{{ url_for('users.settings') }}">Account</a>
          <a href="{{ url_for('users.logout') }}">Logout</a>
          {% else %}
          <a href="{{ url_for('users.device_settings') }}">Settings</a>
          <a href="{{ url_for('users.login') }}">Login</a>
          {% endif %}
          <a id="closeMenu" onClick="toggleMenu()">Close</a>
        </div>
      </nav>
    </header>
    <main>
      {% block templateAddon %}
      {% endblock %}
    </main>
    <footer>
      <div id="footnotes">
        &copy; copyright Sen Tang, 2020 <br>
        version {{version}} <br>
        <a href="{{ url_for('users.report') }}" target="_blank">Report Error</a>
      </div>
    </footer>
  </body>
</html>

project/templates/max-1000.html
{% extends 'base.html' %}

{% block templateAddon %}
  {% for message in get_flashed_messages() %}
  <section class="confined-1000" id='message{{loop.index}}' style="display: block; margin-bottom: 1rem;">
    <div class='notification' onClick = "toggleElement('message{{loop.index}}')">
      {{ message }}
    </div>
  </section>
  {% endfor %}

  <section class="confined-1000">
    {% block mainContent %}
    {% endblock %}
  </section>
{% endblock %}

project/templates/template.html
{% extends 'base.html' %}
{% block templateAddon %}
      <section id="custom-grid1">
        <div id="grid-main">
        </div>
        <div id="grid-side1">
          <h2>Custom-grid Sections</h2>
          <p>These sections are wonderful for presenting information in a non-linear fashion. This is great for using as a splash section on a homepage.</p>
        </div>
        <div id="grid-side2">
          <h2>Separate CSS Sheet</h2>
          <p>Custom-grid sections have their own separate CSS file (custom-grids.css). This way, the custom sections of the CSS file is separate from the rest of the Unilay CSS.</p>
        </div>
        <div id="grid-side3">
          <h2>Responsiveness Enabled</h2>
          <p>Custom sections are not responsive by default, but responsiveness can be added in through the custom CSS file.</p>
        </div>
        <div id="grid-side4">
          <h2>Infinite Customization</h2>
          <p>This is one of the greatest features introduced in Unilay 4, helping projects distinguish themselves from one another.</p>
        </div>
      </section>


      <section class="confined-1000">
        <h1>Welcome to Unilay</h1>
        <p>
          Unilay is a universal web layout for projects at <a href="https://www.sensworks.ca/">sensworks.ca</a> and <a href="https://www.theonline.app/">theonline.app</a>. The aim of Unilay is to provide a uniform look across projects and to take away the hassle of producing a new design for every single app.
        </p>
        <p>
          This is the 4th iteration of Unilay, with a new focus on flexibility, simplicity, and integration with content management systems and flask.
        </p>
        <h2>Confined Sections</h2>
        <p>
          Some sections are not ruled by a CSS grid, but simply confined to a maximum width. This one has a maximum width of 1000px. It is recommended to confine the width of elements so that the viewer does not have to constantly move their eyes from the left of the screen to the right side, especially on bigger screens.
        </p>
        <p class="left-border-decoration">
          Quick Tip: Text with a big red border on the left can be achieved with the <code>class="left-border-decoration"</code>. On a separate note, the confined sections are achieved with the <code>class="confined-1000"</code>.
        </p>

        <h3>Auto-columned class</h3>
        <div class="columns-3">
          <p>
            It might also be advisable to split up text-heavy blocks into columns. Any div with the columns-n class will automatically divide up its content into n columns. This makes text easier to read especially on bigger screens.
            When used in mobile view, column-n class elements will display everything in a single column. Try not to mix up text with divs and images in an element with the columns-n class, as that makes equal divisions difficult. Any divs inside a column-n class element will not break, but retains its grouping as a block.
          </p>
          <p>
            The auto-columned class is <code>class="columns-3"</code>
          </p>
        </div>
        <h3>Images</h3>
        <img src="images/columns.jpg" alt="">
        <p>
          All images, regardless of size, will not exceed its parent container. <code>class="full-width"</code> can also be added to images so even smaller images will take up the entire space. This class gives images the "width: 100%;" property. Images are also given 2rems of margin below them.
        </p>
        <p class="left-border-decoration">
          A quick sidenote: All images used in Unilay are NOT licensed for redistribution. Explicit permission from the image authors are required.
        </p>
      </section>


      <section class="confined-1000">
        <h2>Sections with spaces reserved for sidebars</h2>
        <div class="with-sidebar">
          <div class="section-main">
            <p>Some sections benefit from having a sidebar attached to it. A sidebar can contain navigation links, relevant instructions or help messages, contain notifications, etc.</p>
            <p>This is achived by adding <code>class="with-sidebar"</code> to the containing block-level element, then adding <code>class="section-main"</code> to the main DIV. An <code>aside</code> element should be used to contain the sidebar.</p>
            <h1>Headings (h1)</h1>
            <p>
              I almost forgot, here's a quick run-down of all the headings. A H1 is usually not near the middle of the page, but this is for demonstration only, so we're good, right?
            </p>
            <p>
              While we're here, let's also look at rich-text formatting. Here's some
              <ul>
                <li><strong>bold text</strong></li>
                <li><i>italics</i></li>
                <li><u>underlined text</u></li>
                <li><a href="#">A link</a></li>
                <li>... All inside an unordered list.</li>
              </ul>
            </p>
            <h2>Heading 2</h2>
            <p>
              The most commonly-used heading. You've seen it many times so far.
            </p>
            <h3>Heading 3</h3>
            <h4>Heading 4</h4>
            <h5>Heading 5</h5>
          </div>
          <aside class="">
            <div class="sidebarBlock">
              <h3>Sidebar</h3>
              <a href="#" class="naviLink">Navigation Link</a>
              <a href="#" class="naviLink">Navigation Link</a>
              <a href="#" class="naviLink">Navigation Link</a>
              <p>
                Navigation links in the sidebar should use <code>class="naviLink"</code>.
              </p>
            </div>
          </aside>
        </div>
      </section>

      <section class="confined-1000">
        <h2>Comparison Blocks</h2>
        <p>
          Comparisons are very common when trying to write persuasively. There are comparison-3 blocks and comparison-2 blocks. They're both containers for DIV blocks, displayed using a CSS grid.
        </p>
        <div class="comparison-2">
          <div class="comp1 simple">
            <h3>Comparison Object 1</h3>
          </div>
          <div class="comp2 simple">
            <h3>Comparison Object 2</h3>
          </div>
        </div>
        <div class="comparison-3">
          <div class="comp1 plain">
            <h3>Comparison Object 1</h3>
          </div>
          <div class="comp2 simple">
            <h3>Comparison Object 2</h3>
          </div>
          <div class="comp3 colored">
            <h3>Comparison Object 3</h3>
          </div>
        </div>
      </section>
      <section class="confined-1000">
        <h2>Forms</h2>
        <form>
          <label for="input1">This is a label</label>
          <input type="text" id="input1" name="input1" value="Prefilled Form">
          <input type="number" name="input2" placeholder="Placeholder">
          <select>
            <option>Option 1</option>
            <option>Option 2</option>
          </select>
          <input type="checkbox" id="thecheckbox" value="Check this box">
          <label for="thecheckbox">Check this box</label>

          <p>
            <input type="radio" name="radio1" id="radiooption1">
            <label for="radiooption1">I heard that Radio buttons are all the rage. </label><br>
            <input type="radio" name="radio1" id="radiooption2"> <label for="radiooption2">I don't like Radio buttons. </label>
          </p>
          <textarea name="name" rows="8" cols="80"></textarea>
          <input type="submit" name="input3" value="Submit" class="blueButton">
          <input type="submit" name="input3" value="Submit" class="redButton">
          <button type="button" name="button">Button</button>
        </form>

        <div class="highlightBlock">
          <h3>Quill Rich-Text Editor</h3>
          <p>And of course, the highlight is integration of Quill into forms and the flask framework.</p>
          <p class="left-border-decoration">On form submission, javascript adds the innerHTML of the quillEditor to a hidden form field.</p>
          <div id="quillEditor"></div>
        </div>
      </section>

      <section class="confined-1000" id="contact" style="text-align: center;">
        <img src="images/logo-big.png" style="max-width: 50%;" alt="">
        <h2>Contact Information</h2>
        <p>If you'd like to use Unilay in one of your projects, please contact <em>daryl@sensworks.ca</em></p>
      </section>
      <section class="confined-1000" id="credits" style="text-align: center;">
        <h2>Credits</h2>
        <div>
          <p>HTML and CSS by <a href="https://www.sensworks.ca/" target="_blank">Daryl (Sen)</a></p>
          <p>Rich-text Editor by <a href="https://www.quilljs.com/" target="_blank">Quill</a></p>
          <p>Images used are licensed by <a href="https://www.freepik.com/" target="_blank">freepik.com</a>, under a premium license. Not for redistribution.</p>
        </div>
      </section>
{% endblock %}

project/templates/unconfined.html
{% extends 'base.html' %}

{% block templateAddon %}
  {% for message in get_flashed_messages() %}
  <section class="confined-1000" id='message{{loop.index}}' style="display: block; margin-bottom: 1rem;">
    <div class='notification' onClick = "toggleElement('message{{loop.index}}')">
      {{ message }}
    </div>
  </section>
  {% endfor %}

  {% block mainContent %}
  {% endblock %}
{% endblock %}

project/templates/with-sidebar.html
{% extends 'base.html' %}

{% block templateAddon %}
  {% for message in get_flashed_messages() %}
  <section class="confined-1000" id='message{{loop.index}}' style="display: block; margin-bottom: 1rem;">
    <div class='notification' onClick = "toggleElement('message{{loop.index}}')">
      {{ message }}
    </div>
  </section>
  {% endfor %}

  <section class="confined-1000 with-sidebar">
    <div class="section-main">
      {% block mainContent %}
      {% endblock %}
    </div>
    <aside>
      {% block sidebar %}
      {% endblock %}
    </aside>
  </section>
{% endblock %}