project/pages/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, session
from project import db
import time
from flask_login import login_required, current_user
import datetime
import pytz
from flask_wtf import csrf

from project.core.urlcode import url_encode, url_decode
from project.core.daynight import eval_time
from project.models import Notebooks, Pages, Desks
from project.core.sequencing import page_add, page_delete, page_insert, page_swap
from project.pages.forms import add_page_form, edit_page_form

pages = Blueprint('pages', __name__, template_folder = "templates/pages")

@pages.route('/<int:notebook_id>', methods=['GET', 'POST'])
def show(notebook_id):
    target_notebook = Notebooks.query.get(notebook_id)
    if target_notebook is None:
        flash('Sorry, a notebook with that ID does not exist.')
        return redirect(url_for('core.index'))
    if target_notebook.access_code == "" or (current_user.is_authenticated and target_notebook.owner == current_user.id):
        access = True
    else:
        if session.get('access_key'):
            if session['access_key'] == "{}-{}".format(target_notebook.id, target_notebook.access_code):
                access = True
            else:
                flash('Please enter the access code again.')
                access = False
        else:
            access = False



    if access == True:
        if "daynight_pref" in request.form:
            session['daynight_pref'] = request.form['daynight_pref']

        if request.args.get('p'):
            try:
                page_id = url_decode(request.args.get('p'))
            except:
                flash('There was something wrong with the page ID. Please do not type page IDs manually.')
                return redirect(url_for('pages.show', notebook_id = notebook_id))
            target_page = Pages.query.get(page_id)
            if target_page in target_notebook.pages:
                if target_page.next == 0:
                    next_page_url = 0
                else:
                    next_page_url = url_encode(target_page.next)

                if target_page.prior == 0:
                    prior_page_url = 0
                    return redirect(url_for('pages.show', notebook_id = target_notebook.id))
                else:
                    prior_page_url = url_encode(target_page.prior)

                if current_user.is_authenticated:
                    page_last_update = datetime.datetime.fromtimestamp(int(target_page.last_update)).astimezone(pytz.timezone(current_user.preferences.timezone)).strftime('%d %B, %Y')
                else:
                    page_last_update = datetime.datetime.fromtimestamp(int(target_page.last_update)).astimezone(pytz.timezone('Etc/GMT+7')).strftime('%d %B, %Y')

                return render_template('page.html', webtitle = "{} - {}".format(target_notebook.title, target_page.heading), daynight = eval_time(), notebook = target_notebook, page = target_page, next_page_url = next_page_url, prior_page_url = prior_page_url, page_url = url_encode(target_page.id), page_last_update = page_last_update)
            else:
                flash('The page you requested does not exist within this notebook.')
                return redirect(url_for('pages.show', notebook_id = target_notebook.id))
        else:
            # check if notebook is on active desk
            if current_user.is_authenticated:
                active_desk = Desks.query.get(current_user.active_desk)
                if active_desk in target_notebook.associated_desks:
                    added_to_desk = True
                else:
                    added_to_desk = False
            else:
                added_to_desk = False

            # show contents page
            all_pages = Pages.query.filter_by(notebook = target_notebook.id)

            page_dict = {}
            for page in all_pages:
                page_dict[page.id] = {'heading': page.heading, 'next': page.next, 'url': url_encode(page.id)}
            num_pages = len(page_dict)

            content_objects = []
            content_objects.append(page_dict[all_pages[0].id])


            for i in range(0, num_pages-1):
                content_objects.append(page_dict[content_objects[i]['next']])

            content_objects.pop(0)
            if len(content_objects) == 0:
                content_objects = 0
                next_page_url = 0
            else:
                next_page_url = content_objects[0]['url']

            if current_user.is_authenticated:
                creation_date = datetime.datetime.fromtimestamp(int(target_notebook.creation_date)).astimezone(pytz.timezone(current_user.preferences.timezone)).strftime('%d %B, %Y')
            else:
                creation_date = datetime.datetime.fromtimestamp(int(target_notebook.creation_date)).astimezone(pytz.timezone('Etc/GMT+7')).strftime('%d %B, %Y')

            return render_template('contents.html', webtitle = "{} - Content Page".format(target_notebook.title), daynight = eval_time(), notebook = target_notebook, page = all_pages[0], all_pages = content_objects, next_page_url = next_page_url, creation_date = creation_date, added_to_desk = added_to_desk)
    else:
        return redirect(url_for('notebooks.get_access', notebook_url = target_notebook.url))

@pages.route('/<int:notebook_id>/add', methods=['GET', 'POST'])
# @csrf.exempt
@login_required
def add_page(notebook_id):
    target_notebook = Notebooks.query.get(notebook_id)
    if current_user.id == target_notebook.owner:
        form = add_page_form()
        if form.validate_on_submit():
            new_page_id = page_add(form.heading.data, form.content.data, notebook_id, current_user.id)
            flash('The new page has been created!')
            return redirect(url_for('pages.show', notebook_id = notebook_id, p = url_encode(new_page_id)))
        else:
            for field, error in form.errors.items():
                flash('{} ({} error)'.format(error[0], field))
        return render_template('addpage.html', webtitle = "Adding New Page to {}".format(target_notebook.title), daynight = eval_time(), form = form, notebook = target_notebook)
    else:
        flash("Sorry, you can't add pages to a notebook that doesn't belong to you!")
        return redirect(url_for('pages.show', notebook_id = notebook.id))


@pages.route('/<int:notebook_id>/insert', methods=['GET', 'POST'])
@login_required
def insert_page(notebook_id):
    if request.args.get('p'):
        page_id = int(url_decode(request.args.get('p')))
        target_notebook = Notebooks.query.get(notebook_id)
        if current_user.id == target_notebook.owner:
            form = add_page_form()
            if form.validate_on_submit():
                if request.args.get('pos'):
                    position = request.args.get('pos')
                else:
                    position = "before"
                new_page_id = page_insert(position = position, insertion_point = page_id, rec_heading = form.heading.data, rec_content = form.content.data, rec_notebook_id = notebook_id, rec_author = current_user.id)
                flash('The new page has been created!')
                return redirect(url_for('pages.show', notebook_id = notebook_id, p = url_encode(new_page_id)))
            else:
                for field, error in form.errors.items():
                    flash('{} ({} error)'.format(error[0], field))
            return render_template('addpage.html', webtitle = "Inserting New Page to {}".format(target_notebook.title), daynight = eval_time(), form = form, notebook = target_notebook)
        else:
            flash("Sorry, you can't add pages to a notebook that doesn't belong to you!")
            return redirect('/notebooks/{}'.format(target_notebook.url))
    else:
        flash("You must specify a page ID.")
        return redirect(url_for('notebooks.show_notebook', notebook_id = notebook_id))


@pages.route('/<int:notebook_id>/edit', methods=['GET', 'POST'])
# @csrf.exempt
@login_required
def edit_page(notebook_id):
    if request.args.get('p'):
        page_id = int(url_decode(request.args.get('p')))
        target_notebook = Notebooks.query.get(notebook_id)
        if current_user.id == target_notebook.owner:
            target_page = Pages.query.get(page_id)
            form = edit_page_form(obj = target_page)
            if form.validate_on_submit():
                target_page.heading = form.heading.data
                target_page.content = form.content.data
                target_page.last_update = int(time.time())
                db.session.commit()
                flash('This page has been editted!')
                return redirect(url_for('pages.show', notebook_id = notebook_id, p = url_encode(target_page.id)))
            else:
                for field, error in form.errors.items():
                    flash('{} ({} error)'.format(error[0], field))

            page_url = url_encode(target_page.id)
            return render_template('editpage.html', webtitle = "Editting a Page in {}".format(target_notebook.title), daynight = eval_time(), form = form, notebook = target_notebook, page = target_page, page_url = page_url)
        else:
            flash("Sorry, you can't edit pages on a notebook that doesn't belong to you!")
            return redirect(url_for('pages.show', notebook_id = notebook_id, p = url_encode(target_page.id)))
    else:
        flash('You must provide a page ID')
        return redirect(url_for('pages.show', notebook_id = notebook_id, p = url_encode(target_page.id)))


@pages.route('/<int:notebook_id>/delete')
@login_required
def delete_page(notebook_id):
    if request.args.get('p'):
        page_id = int(url_decode(request.args.get('p')))
        target_notebook = Notebooks.query.get(notebook_id)
        if current_user.id == target_notebook.owner:
            target_page = Pages.query.get(page_id)
            page_delete(page_id)
            db.session.delete(target_page)

project/pages/templates/pages/addpage.html
{% extends 'max-1000.html' %}

{% block mainContent %}
  <h2>Adding New Page</h2>
  <div class="linedBlock">
    <h3>Notebook: {{ notebook.title }}</h3>
    <form method="post" autocomplete="off">
      {{ form.hidden_tag() }}
      {{ form.heading.label }}{{ form.heading() }}
      {{ form.content.label }}{{ form.content() }}
      <div id="quillEditor"></div>
      {{ form.submit(class_="redButton") }}

      {% if request.headers.get('Referer') != None %}
        <a href="{{ request.headers.get('Referer') }}" class="cancel_button">Cancel</a>
      {% else %}
        <a href="{{ url_for('pages.show', notebook_id = notebook.id)}}" class="cancel_button">Return to Overview</a>
      {% endif %}
    </form>
    <script src="{{ url_for('static', filename='js/quill.js') }}?v={{version}}"></script>
    <script type="text/javascript">
      var toolbarOptions = [
        ['bold', 'italic', 'underline'],
        [{ 'header': [2, 3, 4, 5, false] }],
        {% if current_user.preferences.coding_addon == 1 %}
        ['code', 'code-block'],
        {% endif %}
        {% if current_user.preferences.coding_addon == 1 %}
        ['link'],
        {% endif %}
        // [{ 'list': 'ordered'}, { 'list': 'bullet' }],
        ['clean'],
      ];

      var quill = new Quill('#quillEditor', {
        modules: {
          toolbar: toolbarOptions
        },
        {% if session['editor_pref'] %}
        theme: "{{session['editor_pref']}}", // device settings
        {% else %}
        theme: 'snow', // default settings
        {% endif %}
        scrollingContainer: 'body'
      });

      // quill.root.innerHTML = document.querySelector('input[name=content]').value;
      var form = document.querySelector('form');
      form.onsubmit = function() {
        // Populate hidden form on submit
        var about = document.querySelector('input[name=content]');
        var editorContent = quill.root.innerHTML;
        about.value = editorContent;
      };

      document.querySelectorAll(".ql-picker").forEach(tool => {
      tool.addEventListener("mousedown", function(event) {
        event.preventDefault();
        event.stopPropagation();
      });
    });
    </script>
  </div>
{% endblock %}

project/pages/templates/pages/contents.html
{% extends 'with-sidebar.html' %}

{% block mainContent %}
  <h1>{{ notebook.title}}</h1>
  <p class="timestamp">Created on {{ creation_date }}</p>

  <img src="{{notebook.cover_img}}" alt="" class="notebookCover">

  <p>{{ notebook.desc }}</p>
  <div class="spacer"></div>
    <h2>Notebook Contents</h2>
  {% if all_pages != 0 %}
    {% for page in all_pages %}
      {% if page.heading[0:8] == "DIVIDER:" %}
        <div class="divider">{{ page.heading[8:] }} {% if current_user.is_authenticated and current_user.id == notebook.owner %}(<a href="{{ url_for('pages.edit_page', notebook_id = notebook.id, p = page.url) }}">Edit</a> / <a onClick="return confirm('This divider page will be deleted, are you sure?');" href="{{ url_for('pages.delete_page', notebook_id = notebook.id, p = page.url)}}">Delete</a>){% endif %}</div>
      {% else %}
        <a href="{{ url_for('pages.show', notebook_id = notebook.id, p=page.url)}}" class="naviLink">{{page.heading}}</a>
      {% endif %}
    {% endfor %}
  {% else %}
    <p>There are no pages in this notebook. {% if current_user.id == notebook.owner %}Please <a href="{{ url_for('pages.add_page', notebook_id = notebook.id)}}">add a new page</a>!{% endif %}</p>
  {% endif %}

  <div id="toggles">
    <a href="{{ url_for('users.device_settings') }}" target="_blank"><button class="toggleButton blueButton">&#9881;</button></a>
    {% if session['keywords_pref'] and session['keywords_pref'] == "OFF" %}
    {% else %}
      <button class="toggleButton redButton" id="toggleKeywordsButton" onClick="hideKeywords();">K</button>
    {% endif %}
    {% if daynight == "DAY" %}
      {% if session['daynight_pref'] == "NIGHT" %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton yellowButton" value="DAY">&#9728;</button>
      </form>
      {% else %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton darkButton" value="NIGHT">&#9728;</button>
      </form>
      {% endif %}
    {% elif daynight == "NIGHT" %}
      {% if session['daynight_pref'] == "DAY" %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton darkButton" value="NIGHT">&#9728;</button>
      </form>
      {% else %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton yellowButton" value="DAY">&#9728;</button>
      </form>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}






{% block sidebar %}
  <div class="sidebarBlock">
    <h4>Navigation</h4>
    {% if page.next != 0 %}
      <a href="{{ url_for('pages.show', notebook_id = notebook.id, p = next_page_url) }}" class="naviLink">Go to Page 1</a>
    {% endif %}





    {% if added_to_desk == False %}
      <a href="{{ url_for('notebooks.add_notebook', notebook_id = notebook.id)}}" class="naviLink">Add to My Desk</a>
    {% elif added_to_desk == True %}
      <a href="{{ url_for('notebooks.remove_notebook', notebook_id = notebook.id, desk_id = current_user.active_desk, backref=notebook.id) }}" class="naviLink">Remove from Desk</a>
    {% endif %}




    <a href="{{ url_for('users.report')}}" class="naviLink">Report This Notebook</a>
  </div>
  {% if current_user.id == notebook.owner %}
    <div class="sidebarBlock">
      <h4>Notebook Options</h4>
      <a href="{{ url_for('notebooks.edit_notebook', notebook_url = notebook.url)}}" class="naviLink">Edit Notebook Info</a>
      <a onClick = "return alert('This feature is coming soon! In the meantime, you can find the option to insert, edit, or delete pages on the page itself.')" class="naviLink">Manage Pages</a>
      <a href="{{ url_for('pages.add_page', notebook_id = notebook.id)}}" class="naviLink">Add a New Page</a>
      <a onClick="return confirm('Are you sure you want to delete this notebook? This action is IRREVERSIBLE!');" href="{{ url_for('notebooks.delete_notebook', notebook_id = notebook.id)}}" class="naviLink">DELETE</a>
    </div>
    <div class="dashedBlock">
      <h4>{% if notebook.access_code != "" %}&#128274; {% endif %}Descriptive Link</h4>
      <span class="shareURL">www.fluidnotebook.com/u/{{notebook.associated_user.username}}/{{notebook.url}}</span>
    </div>
  {% else %}
    <div class="dashedBlock">
      <h4>Read-Only</h4>
      <p>Owner: <b><a href="{{url_for('notebooks.profile', username = notebook.associated_user.username)}}">{{notebook.associated_user.username}}</a></b></p>
      <h4>{% if notebook.access_code != "" %}&#128274; {% endif %}Share Link</h4>
      <span class="shareURL">www.fluidnotebook.com/u/{{notebook.associated_user.username}}/{{notebook.url}}</span>
    </div>
  {% endif %}
{% endblock %}

project/pages/templates/pages/editpage.html
{% extends 'max-1000.html' %}

{% block mainContent %}
  <h2>Editting a Page</h2>
  <div class="linedBlock">
    <h3>Notebook: {{ notebook.title }}</h3>
    <form method="post" autocomplete="off">
      {{ form.hidden_tag() }}
      {{ form.heading.label }}{{ form.heading() }}
      {{ form.content.label }}{{ form.content() }}
      <div id="quillEditor"></div>
      {{ form.submit(class_="redButton") }}
      <a href="{{ url_for('pages.show', notebook_id = notebook.id, p=page_url)}}" class="cancel_button">Cancel</a>
    </form>
    <script src="{{ url_for('static', filename='js/quill.js') }}?v={{version}}"></script>
    <!-- <script src="{{ url_for('static', filename='js/quill-instance.js') }}?v={{version}}"></script> -->
    <script type="text/javascript">

      var toolbarOptions = [
      ['bold', 'italic', 'underline'],
      [{ 'header': [2, 3, 4, 5, false] }],
      {% if current_user.preferences.coding_addon == 1 %}
      ['code', 'code-block'],
      {% endif %}
      {% if current_user.preferences.coding_addon == 1 %}
      ['link'],
      {% endif %}
      // [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      ['clean'],
      ];

      var quill = new Quill('#quillEditor', {
        modules: {
          toolbar: toolbarOptions
        },
        {% if session['editor_pref'] %}
        theme: "{{session['editor_pref']}}", // device settings
        {% else %}
        theme: 'snow', // default settings
        {% endif %}
        scrollingContainer: 'body'
      });

      // quill.root.innerHTML = document.querySelector('input[name=content]').value;
      var form = document.querySelector('form');
      form.onsubmit = function() {
        // Populate hidden form on submit
        var about = document.querySelector('input[name=content]');
        var editorContent = quill.root.innerHTML;
        about.value = editorContent;
      };

      quill.root.innerHTML = document.querySelector('input[name=content]').value;

      document.querySelectorAll(".ql-picker").forEach(tool => {
      tool.addEventListener("mousedown", function(event) {
        event.preventDefault();
        event.stopPropagation();
      });
    });
    </script>
  </div>
{% endblock %}

project/pages/templates/pages/page.html
{% extends 'with-sidebar.html' %}

{% block mainContent %}

  <h1>{{page.heading}}</h1>
  {{page.content | safe }}

  <div class="spacer"></div>
  <p class="timestamp">Last Updated on: {{ page_last_update }}</p>
  <section class="comparison-2" style="margin-top: 2rem; text-align: center;">
    <div class="comp1 simple">


      {% if prior_page_url != 0 %}
        <a href="{{ url_for('pages.show', notebook_id = notebook.id, p = prior_page_url) }}">&larr; Previous Page</a>
      {% else %}
        Start of Document
      {% endif %}
    </div>
    <div class="comp2 simple">
      {% if next_page_url != 0 %}
        <a href="{{ url_for('pages.show', notebook_id = notebook.id, p = next_page_url) }}">&rarr; Next Page</a>
      {% else %}
        End of Document
      {% endif %}
    </div>
  </section>

  <div id="toggles">
    <a href="{{ url_for('users.device_settings') }}" target="_blank"><button class="toggleButton blueButton">&#9881;</button></a>
    {% if session['keywords_pref'] and session['keywords_pref'] == "OFF" %}
    {% else %}
      <button class="toggleButton redButton" id="toggleKeywordsButton" onClick="hideKeywords();">K</button>
    {% endif %}
    {% if daynight == "DAY" %}
      {% if session['daynight_pref'] == "NIGHT" %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton yellowButton" value="DAY">&#9728;</button>
      </form>
      {% else %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton darkButton" value="NIGHT">&#9728;</button>
      </form>
      {% endif %}
    {% elif daynight == "NIGHT" %}
      {% if session['daynight_pref'] == "DAY" %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton darkButton" value="NIGHT">&#9728;</button>
      </form>
      {% else %}
      <form action="" method="post">
        <button name="daynight_pref" class="toggleButton yellowButton" value="DAY">&#9728;</button>
      </form>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}

{% block sidebar %}
  <div class="sidebarBlock">
    <h4>{{notebook.title}}</h4>
    <a href="{{ url_for('pages.show', notebook_id = notebook.id)}}" class="naviLink">Return to Contents</a>
  </div>

  {% if current_user.is_authenticated and current_user.id == notebook.owner %}
    <div class="sidebarBlock">
      <h4>Page Options</h4>
      <a href="{{ url_for('pages.edit_page', notebook_id = notebook.id, p = page_url) }}" class="naviLink">Edit Page</a>
      <a href="{{ url_for('pages.insert_page', notebook_id = notebook.id, p = page_url, pos = 'before')}}" class="naviLink">Insert Page Before</a>
      {% if page.next != 0 %}
         <a href="{{ url_for('pages.insert_page', notebook_id = notebook.id, p = page_url, pos = 'after')}}" class="naviLink">Insert Page After</a>
      {% endif %}
      <a href="{{ url_for('pages.add_page', notebook_id=notebook.id)}}" class="naviLink">Add Page</a>
      {% if page.prior != 0 %}
        <a onClick="return confirm('Are you sure you want to delete this page?');" href="{{ url_for('pages.delete_page', notebook_id = notebook.id, p = page_url)}}" class="naviLink">Delete Page</a>
      {% endif %}
    </div>
  {% else %}
  <div class="dashedBlock">
    <h4>Read-Only</h4>
    <p>Owner: <b><a href="{{url_for('notebooks.profile', username = notebook.associated_user.username)}}">{{notebook.associated_user.username}}</a></b></p>
    <h4>Descriptive Link</h4>
    <span class="shareURL">www.fluidnotebook.com/notebooks/{{notebook.url}}</span>
  </div>
  {% endif %}
{% endblock %}