project/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from project import db, mail
from flask_mail import Message
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash
from project.core.daynight import eval_time
import time

#forms
from project.users.forms import login_form, registration_form, changePassword_form, report_form, preferences_form, profile_form, pw_reset_form, pw_reset_request_form, email_login_form

# #models
from project.models import Users, Desks, Reports, Preferences


accounts = Blueprint('users', __name__, template_folder = "templates/users")

@accounts.route('/login', methods=['POST', 'GET'])
def login():
    form = login_form()
    if form.validate_on_submit():
        this_user = Users.query.filter_by(username = form.username.data.lower()).first()
        if this_user is not None and this_user.check_password(form.password.data):
            login_user(this_user)
            flash('Logged In')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('desks.index')
            return redirect(next)
        else:
            flash('You have provided a wrong username or password.')
            return redirect(url_for('users.login'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('login.html', webtitle = "Log In", daynight = eval_time(), form = form)


@accounts.route('/email_login', methods=['POST', 'GET'])
def email_login():
    form = email_login_form()
    if form.validate_on_submit():
        this_user = Users.query.filter_by(email = form.email.data.lower()).first()
        if this_user is not None and this_user.check_password(form.password.data):
            login_user(this_user)
            flash('Logged In')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('desks.index')
            return redirect(next)
        else:
            flash('You have provided a wrong email or password.')
            return redirect(url_for('users.email_login'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('email_login.html', webtitle = "Log In", daynight = eval_time(), form = form)



@accounts.route('/signup', methods=['POST', 'GET'])
def register():
    form = registration_form()
    if form.validate_on_submit():
        new_user = Users(username = form.username.data.lower(), email = form.email.data, password = form.password.data, bio = "", pic = "https://www.fluidnotebook.com/static/images/defaultavatar.png", active_desk = 0)
        db.session.add(new_user)
        db.session.commit()
        new_desk = Desks(deskname = "Main Desk", desc = ("The primary desk that's setup for {}.".format(new_user.username)), owner = new_user.id)
        db.session.add(new_desk)
        db.session.commit()
        new_user.active_desk = new_desk.id
        user_prefs = Preferences(timezone = "Etc/GMT+8", night_on = 21, night_off = 7, night_type = "dark", font_size = "18", coding_addon = 0, hyperlinks_addon = 0, colors_addon = 0, user_id = new_user.id)
        db.session.add(user_prefs)
        db.session.commit()
        flash("Your account has been registered, please log in!")
        return redirect(url_for('users.login'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('register.html', webtitle = "Register an Account", daynight = eval_time(), form = form)


@accounts.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out.')
    return redirect(url_for('core.index'))


@accounts.route('/change_password', methods = ['GET', 'POST'])
@login_required
def change_password():
    this_user = Users.query.get(current_user.id)
    form = changePassword_form()
    if form.validate_on_submit():
        if this_user.check_password(form.current_pw.data):
            this_user.password = generate_password_hash(form.new_pw.data)
            db.session.commit()
            flash('Password Changed.')
            return redirect(url_for('users.settings'))
        else:
            print(generate_password_hash(form.current_pw.data))
            print(this_user.password)
            flash('Your current password is wrong, please try again.')
            return redirect(url_for('users.change_password'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('changepassword.html', webtitle = "Change Password", daynight = eval_time(), form = form)



@accounts.route('/report', methods = ['POST', 'GET'])
def report():
    form = report_form()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            reporter = current_user.username
        else:
            reporter = "unauthenticated"
        new_report = Reports(type = form.type.data, url = form.url.data, content = form.content.data, user = reporter, date = int(time.time()))
        db.session.add(new_report)
        db.session.commit()
        flash('Your report has been submitted, thank you!')
        return redirect(url_for('users.report'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('report.html', webtitle = "Report", daynight = eval_time(), form = form)



@accounts.route('/myinfo', methods = ['POST', 'GET'])
@login_required
def change_info():
    target_user = Users.query.get(current_user.id)
    form = profile_form(obj = target_user)
    if form.validate_on_submit():
        target_user.bio = form.bio.data
        target_user.email = form.email.data
        target_user.pic = form.pic.data
        db.session.commit()
        flash('Your details have been updated.')
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('myinfo.html', webtitle = "My Information", daynight = eval_time(), form = form)



@accounts.route('/settings', methods = ['POST', 'GET'])
@login_required
def settings():
    return render_template('settings.html', webtitle = "Settings", daynight = eval_time())



@accounts.route('/preferences', methods = ['GET', 'POST'])
@login_required
def preferences():
    user_prefs = Preferences.query.filter_by(user_id = current_user.id).first()
    form = preferences_form(obj = user_prefs)
    if form.validate_on_submit():
        user_prefs.timezone = form.timezone.data
        user_prefs.night_time_on = form.night_time_on.data
        user_prefs.night_time_off = form.night_time_off.data
        user_prefs.night_mode_type = form.night_mode_type.data
        user_prefs.font_size = form.font_size.data
        user_prefs.coding_addon = form.coding_addon.data
        user_prefs.hyperlinks_addon = form.hyperlinks_addon.data
        user_prefs.colors_addon = form.colors_addon.data
        db.session.commit()
        flash('Settings Updated.')
        return redirect(url_for('users.settings'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))
    return render_template('preferences.html', webtitle = "Account Preferences", daynight = eval_time(), form = form)



@accounts.route('/device', methods = ['GET', 'POST'])
def device_settings():
    if "modified_settings" in request.form:
        if request.form['daynight_pref'] != "AUTO":
            session['daynight_pref'] = request.form['daynight_pref']
        elif request.form['daynight_pref'] == "AUTO" and session.get('daynight_pref'):
            session.pop('daynight_pref')

        if request.form['font_size_pref'] != "AUTO":
            session['font_size_pref'] = request.form['font_size_pref']
        session['keywords_pref'] = request.form['keywords_pref']

        if "editor_pref" in request.form:
            session['editor_pref'] = request.form['editor_pref']


    if request.args.get('clear'):
        if request.args.get('clear') == "session":
            if session.get('daynight_pref'):
                session.pop('daynight_pref')
            if session.get('font_size_pref'):
                session.pop('font_size_pref')
            if session.get('keywords_pref'):
                session.pop('keywords_pref')
            if session.get('editor_pref'):
                session.pop('editor_pref')

            flash('Your device-specific settings have been cleared.')

    return render_template('device_settings.html', webtitle = "Device-Specific Settings", daynight = eval_time())



@accounts.route('/forgot_password', methods = ['GET', 'POST'])
def forgot_password():
    if current_user.is_authenticated:
        flash("Actually, you're already logged in.")
        return redirect(url_for('core.index'))
    else:
        form = pw_reset_request_form()
        if form.validate_on_submit():
            target_user = Users.query.filter_by(email = form.email.data).first()
            token = target_user.get_reset_token()
            email_message = Message('Password Reset Request', sender = 'noreply@sensworks.ca', recipients = [target_user.email])
            email_message.body = f"""Hey {target_user.username}, \n
I heard that you forgot your password for your account at Fluid Notebook. Please click on the following link to reset it. \n
{url_for('users.reset_password', token = token, _external = True)}\n
This link will expire in 30 mins, please do not share it with anyone, as they'll be able to change your password.\n\n
Thanks for using Fluid Notebook!\n
Daryl"""
            mail.send(email_message)

project/users/templates/users/changepassword.html
{% extends 'max-1000.html' %}

{% block mainContent %}
<h1>Change Password</h1>
<div class="linedBlock">
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.current_pw.label }}{{ form.current_pw() }}
    {{ form.new_pw.label }}{{ form.new_pw() }}
    {{ form.cfm_pw.label }}{{ form.cfm_pw() }}
    {{ form.submit(class_="redButton") }}
  </form>
  <a href="{{ url_for('users.settings') }}" class="cancel_button">Back to Settings</a>
</div>
{% endblock %}

project/users/templates/users/device_settings.html
{% extends 'max-1000.html' %}

{% block mainContent %}
  <h1>Fluid Notebook Settings</h1>
  {% if current_user.is_authenticated %}
    <p>The following settings are specific to this device. These will override any <a href="{{ url_for('users.preferences') }}">account preferences</a> you have.</p>
  {% else %}
    <p>Welcome to Fluid Notebook. The following are some settings you can choose to optimize your viewing experience. You do not need an account, and these settings will only apply to this current device.</p>
    <p>Do consider <a href="{{ url_for('users.register') }}">signing up</a> to create your own notebooks and get access to many more settings and features!</p>
  {% endif %}

  {% if session['daynight_pref'] %}
    {% if session['daynight_pref'] == "DAY" %}
      {% set day_marker = " checked = checked" %}
      {% set night_marker = "" %}
      {% set default_marker = "" %}
    {% else %}
      {% set day_marker = "" %}
      {% set night_marker = " checked = checked" %}
      {% set default_marker = "" %}
    {% endif %}
  {% else %}
    {% set day_marker = "" %}
    {% set night_marker = "" %}
    {% set default_marker = " checked = checked" %}
  {% endif %}

  {% if session['keywords_pref'] %}
    {% if session['keywords_pref'] == "ON" %}
      {% set keywords_on_marker = " checked = checked" %}
      {% set keywords_off_marker = "" %}
    {% else %}
      {% set keywords_on_marker = "" %}
      {% set keywords_off_marker = " checked = checked" %}
    {% endif %}
  {% else %}
    {% set keywords_on_marker = " checked = checked" %}
    {% set keywords_off_marker = "" %}
  {% endif %}

  {% if session['editor_pref'] %}
    {% if session['editor_pref'] == "snow" %}
      {% set editor_snow_marker = " checked = checked" %}
      {% set editor_bubble_marker = "" %}
    {% else %}
      {% set editor_snow_marker = "" %}
      {% set editor_bubble_marker = " checked = checked" %}
    {% endif %}
  {% else %}
    {% set editor_snow_marker = " checked = checked" %}
    {% set editor_bubble_marker = "" %}
  {% endif %}
  {% if request.headers.get('Referer') != None and request.headers.get('Referer') != url_for(request.url_rule.endpoint, _external = True) %}
      <a href="{{ request.headers.get('Referer') }}" class="cancel_button">Back</a>
  {% endif %}

    <form action="{{ url_for('users.device_settings') }}" method="post">

      {% if session['daynight_pref'] or session['font_size_pref'] or session['keywords_pref'] %}
      <div class="notification">
        <p>Device-specific settings are on for this device. This overrides your account preferences, please clear these settings to conform to your account preferences. <a href="{{ url_for('users.device_settings', clear='session')}}">Clear settings</a>.</p>
      </div>
      {% endif %}

      <div class="linedBlock">
        <h4>Night Mode</h4>
        <p>If you're using Fluid Notebook under dim lighting conditions, you can turn on Night Mode to switch to a darker color scheme.</p>
        <input type="radio" name="daynight_pref" id="daynight_day" value="DAY"{{day_marker}}>
        <label for="daynight_day">Night Mode OFF</label>
        <br>
        <input type="radio" name="daynight_pref" id="daynight_night" value="NIGHT"{{night_marker}}>
        <label for="daynight_night">Night Mode ON</label>
        <br>
        <input type="radio" name="daynight_pref" id="daynight_auto" value="AUTO"{{default_marker}}>
        <label for="daynight_auto">Night Mode Auto</label>
      </div>

      <div class="linedBlock">
        <h4>Font Size</h4>
        <label for="font_size_pref">Font Size</label>
        <select name="font_size_pref">
          {% if session['font_size_pref'] %}
            <option value="{{ session['font_size_pref'] }}">Current ({{ session['font_size_pref'] }}px)</option>
          {% else %}
            <option value="AUTO">Auto: Medium</option>
          {% endif %}
          <option value="12">Extra Small (12px)</option>
          <option value="15">Small (15px)</option>
          <option value="18">Medium (18px)</option>
          <option value="21">Large (21px)</option>
          <option value="24">Extra Large (24px)</option>
        </select>
      </div>

      <div class="linedBlock">
        <h4>Keywords</h4>
        <p>Keywords is a feature that allows you to quickly conceal underlined words in a notebook. This helps with memorization by creating a fill-in-the-blanks quiz on the fly.</p>
        <p>If you prefer to turn this feature off, you can do it here.</p>
        <input type="radio" name="keywords_pref" id="keywords_on" value="ON"{{keywords_on_marker}}>
        <label for="keywords_on">Keywords ON</label>
        <br>
        <input type="radio" name="keywords_pref" id="keywords_off" value="OFF"{{keywords_off_marker}}>
        <label for="keywords_off">Keywords OFF</label>
      </div>

      {% if current_user.is_authenticated %}
        <div class="linedBlock">
          <h4>Editor Style</h4>
          <p>Fluid Notebook uses Quill, which comes with two styles for rich-text editing. By default, the "Snow" style is used, where the controls are at the top of the editting box. The "Bubble" style features an extremely minimialistic interface, with controls showing up only after you highlight some text.</p>
          <p>"Bubble" might be better if you often create very long pages, which forces you to scroll back up to access the controls. Since controls appear right below highlighted text in "Bubble", it follows you throughout the page.</p>
          <input type="radio" name="editor_pref" id="editor_snow" value="snow"{{editor_snow_marker}}>
          <label for="editor_snow">Snow Style</label>
          <br>
          <input type="radio" name="editor_pref" id="editor_bubble" value="bubble"{{editor_bubble_marker}}>
          <label for="editor_bubble">Bubble Style</label>
        </div>
      {% endif %}

      <input type="hidden" name="modified_settings" value="True">
      <input type="submit" value="Apply Settings" class="redButton">
    </form>
    {% if request.headers.get('Referer') != None and request.headers.get('Referer') != url_for(request.url_rule.endpoint, _external = True) %}
      <a href="{{ request.headers.get('Referer') }}" class="cancel_button">Back</a>
    {% else %}
      <a href="{{ url_for('users.settings') }}" class="cancel_button">Back to Settings</a>
    {% endif %}
{% endblock %}

project/users/templates/users/email_login.html
{% extends 'max-1000.html' %}

{% block mainContent %}
<h1>Log In With Email</h1>
<p>If you've forgotten your username, you can log in with your email address. After logging in, please go to your account settings to see your username.</p>
<div class="highlightBlock">
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.email.label }}{{ form.email() }}
    {{ form.password.label }}{{ form.password() }}
    {{ form.submit(class_="redButton") }}
  </form>
  <div class="comparison-3 centered">
    <div class="comp1 plain">
      Forgot Password?
      <a href="{{url_for('users.forgot_password')}}" class="naviLink">Reset Password</a>
    </div>
    <div class="comp2 plain">
      Forgot Email Address?
      <a href="{{url_for('users.login')}}" class="naviLink">Login with Username</a>
    </div>
    <div class="comp3 plain">
      No Account?
      <a href="{{url_for('users.register')}}" class="naviLink">Sign Up</a>
    </div>
  </div>
</div>

{% endblock %}

project/users/templates/users/forgot_password.html
{% extends 'max-1000.html' %}

{% block mainContent %}

<h1>Forgot Password</h1>
<p>We all forget sometimes, trust me, I know. You can reset your password using the form below.</p>
<div class="linedBlock">
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.email.label }}{{ form.email() }}
    {{ form.submit(class_="redButton") }}
  </form>
</div>
{% endblock %}

project/users/templates/users/login.html
{% extends 'max-1000.html' %}

{% block mainContent %}
<h1>Log In</h1>
<div class="highlightBlock">
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}{{ form.username() }}
    {{ form.password.label }}{{ form.password() }}
    {{ form.submit(class_="redButton") }}
  </form>
  <div class="comparison-3 centered">
    <div class="comp1 plain">
      <h4>Forgot Password?</h4>
      <a href="{{url_for('users.forgot_password')}}" class="naviLink">Reset Password</a>
    </div>
    <div class="comp2 plain">
      <h4>Forgot Username?</h4>
      <a href="{{url_for('users.email_login')}}" class="naviLink">Login with Email</a>
    </div>
    <div class="comp3 plain">
      <h4>No Account?</h4>
      <a href="{{url_for('users.register')}}" class="naviLink">Sign Up</a>
    </div>
  </div>
</div>

{% endblock %}

project/users/templates/users/myinfo.html
{% extends 'max-1000.html' %}

{% block mainContent %}
<h1>Personal Details</h1>
<p>Fluid Notebook aims to store <b>as little personal information as possible</b>. Even big companies with well-protected databases will have breaches, so anything you put online is NOT SAFE.</p>
<p>Therefore, Fluid Notebook DOES NOT store ANY payment information or transaction details. All payments go through verified external vendors.</p>
<p>To protect yourself as a user, DO NOT post any personal details, or personally-identifiable images.</p>
<div class="linedBlock">
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.bio.label() }}{{ form.bio() }}
    {{ form.email.label() }}{{ form.email() }}
    {{ form.pic.label() }}{{ form.pic() }}
    {{ form.submit(class_="redButton") }}
  </form>
  <a href="{{ url_for('users.settings') }}" class="cancel_button">Back to Settings</a>
  <p>Your bio and profile picture can be seen on <a href="{{ url_for('notebooks.profile', username = current_user.username)}}">your profile page</a>.</p>
  <p>Your email address is strictly for password recovery and IMPORTANT notices only. Fluid Notebook will never send you spam or promotional emails, or share your email address with a third party.</p>
</div>
{% endblock %}

project/users/templates/users/preferences.html
{% extends 'max-1000.html' %}

{% block mainContent %}
<h1>Account Preferences</h1>
<p>
  You can customize Fluid Notebooks to make it even better for you! When you're done, please click on "Apply Changes" at the bottom of the page to save your settings!
</p>
{% if session['daynight_pref'] or session['font_size_pref'] or session['keywords_pref'] %}
  <div class="notification">
    <b>NOTE:</b> You have device-specific settings turned on for this device, which overrides your account preferences. You can <a href="{{ url_for('users.device_settings') }}">reset those settings here</a>.
  </div>
{% endif %}
<form method="post">
{{ form.hidden_tag() }}
  <div class="linedBlock">
    <h4>Night Mode Settings</h4>
    <p>Customize night mode to reduce eye strain when using Fluid Notebook in dimly-lit conditions.</p>
    {{ form.timezone.label }}{{ form.timezone() }}
    {{ form.night_time_on.label }}{{ form.night_time_on() }}
    <p><b>ONSET TIME:</b> Night mode will turn on automatically at the ONSET time. By default, this is set at 21 (9 PM).</p>
    {{ form.night_time_off.label }}{{ form.night_time_off() }}
    <p><b>OFF TIME:</b> Night mode will turn off automatically at the OFF time. Be default, this is set at 7 (7 AM).</p>
    {{ form.night_mode_type.label }}<br/>
    {% for subfield in form.night_mode_type %}
      {{ subfield }}
      {{ subfield.label }}<br />
    {% endfor %}
    <p>If "No nightmode" is selected, you won't be able to turn on Night Mode even by clicking on the toggle.</p>
  </div>
  <div class="linedBlock">
    <h4>Notebook Display</h4>
    {{ form.font_size.label }}{{ form.font_size() }}
  </div>
  <div class="linedBlock">
    <h4>Addon Editor Functions</h4>
    <p>Fluid Notebook aims to provide a clean user interface. If you need more editing features, you can enable the following addons.</p>
    <b>{{ form.coding_addon() }}{{ form.coding_addon.label }}</b> - allows the use of code snippet and code block highlighting<br/>
    <b>{{ form.hyperlinks_addon() }}{{ form.hyperlinks_addon.label }}</b> - allows adding hyperlinks<br/>
    <!-- <b>{{ form.colors_addon() }}{{ form.colors_addon.label }}</b> - allows changing text color and background<br/> -->
  </div>
    {{ form.submit(class_="redButton") }}
</form>
<a href="{{ url_for('users.settings') }}" class="cancel_button">Back to Settings</a>

{% endblock %}

project/users/templates/users/register.html
{% extends 'max-1000.html' %}

{% block mainContent %}
<h1>Register</h1>
<div class="highlightBlock">
   <p>Please note that Fluid Notebook is currently in beta, this means that some features may be unstable. Use at your own risk!</p>
   <form method="post">
    {{ form.hidden_tag() }}
    {{ form.email.label }}{{ form.email() }}
    {{ form.username.label }}{{ form.username }}
    {{ form.password.label }}{{ form.password() }}
    {{ form.password_cfm.label }}{{ form.password_cfm }}
    <p>By clicking on the "Register" button below, you accept all <a href="https://www.fluidnotebook.com/nb/2?p=NA%3D%3D">terms of use</a> and the <a href="https://www.fluidnotebook.com/nb/2?p=NDg%3D">privacy policy</a>, which are subject to change. You also declare that you are above 13 years of age.</p>
    {{ form.submit(class_="redButton") }}
  </form>
</div>
<p>Have an account? <a href="{{url_for('users.login')}}">Log in here</a>.</p>
{% endblock %}

project/users/templates/users/report.html
{% extends 'max-1000.html' %}

{% block mainContent %}
  <h1>Sending a Report</h1>
  <p>Please help improve Fluid Notebook by sending in reports of issues/errors on the website, and report any public notebooks that contains content that violates the rules.</p>
  <p>DMCA Takedown Requests: Fluid Notebook contains user-generated content. If you found that a notebook contains content that violates your copyright, and your claim will be assessed as soon as possible.</p>
  <div class="linedBlock">
    <form method="post">
      {{ form.hidden_tag() }}
      {{ form.type.label }}{{ form.type() }}
      {{ form.title.label }}{{ form.title() }}
      {{ form.url.label }}{{ form.url() }}
      {{ form.content.label }}{{ form.content() }}
      {{ form.submit(class_="redButton") }}
    </form>
    {% if request.headers.get('Referer') != None and request.headers.get('Referer') != url_for(request.url_rule.endpoint, _external = True) %}
      <a href="{{ request.headers.get('Referer') }}" class="cancel_button">Cancel and Go Back</a>
    {% endif %}
  </div>
{% endblock %}

project/users/templates/users/reset_password.html
{% extends 'max-1000.html' %}

{% block mainContent %}

<h1>Reset Password</h1>
<p>Now that you're verified, please go ahead and set a new password.</p>
<div class="linedBlock">
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.password.label }}{{ form.password() }}
    {{ form.password_cfm.label }}{{ form.password_cfm() }}
    {{ form.submit(class_="redButton") }}
  </form>
</div>
{% endblock %}

project/users/templates/users/settings.html
{% extends 'max-1000.html' %}

{% block mainContent %}
  <h1>Account Settings ({{current_user.username}})</h1>

  <div class="comparison-2">
    <div class="comp-1 simple">
      <h2>Account Preferences</h2>
      <p>Customize the way Fluid Notebook works for you, including features like automatic night mode, font size, and additional features.</p>
      <a class="naviLink" href="{{ url_for('users.preferences') }}">Go to Preferences</a>
    </div>
    <div class="comp-2 simple">
      <h2>Device-Specific Settings</h2>
      <p>You might have different preferences for different devices. These settings will override your account preferences.</p>
      <a class="naviLink" href="{{ url_for('users.device_settings') }}">Go to Device Settings</a>
    </div>
  </div>
  <div class="comparison-2">
    <div class="comp-1 simple">
      <h2>My Profile</h2>
      <p>Make changes to your profile page, and review your contact info. Any personal info you provided will be stored here.</p>
      <a class="naviLink" href="{{ url_for('users.change_info') }}">Edit My Profile</a>
    </div>
    <div class="comp-2 simple">
      <h2>Change Password</h2>
      <p>You can change your password here. Please do not use the same password across different websites!</p>
      <a class="naviLink" href="{{ url_for('users.change_password') }}">Change Password</a>
    </div>
  </div>
{% endblock %}