project/desks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField, IntegerField, PasswordField
from wtforms.validators import DataRequired, URL, Length

class add_desk_form(FlaskForm):
    deskname = StringField('Desk Name', validators = [DataRequired("You must enter a desk name, or you'll have a hard time finding it later."), Length(min = 1, max = 20, message = "The desk name must be between 1-20 characters.")])
    desc = TextAreaField('Desk Description')
    submit = SubmitField('Add Desk')

class edit_desk_form(FlaskForm):
    deskname = StringField('Desk Name', validators = [DataRequired("You must enter a desk name, or you'll have a hard time finding it later."), Length(min = 1, max = 20, message = "The desk name must be between 1-20 characters.")])
    desc = TextAreaField('Desk Description')
    submit = SubmitField('Edit Desk')

project/desks/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from project import db
from flask_login import login_required, current_user

from project.core.daynight import eval_time
from project.models import Users, Desks, Notebooks
from project.desks.forms import add_desk_form, edit_desk_form

desks = Blueprint('desks', __name__, template_folder = "templates/desks")

@desks.route('/')
@login_required
def index():
    active_desk = Desks.query.get(current_user.active_desk)

    #FIND NOTEBOOKS ON THIS DESK (many-to-many filter)
    desk_notebooks = Notebooks.query.filter(Notebooks.associated_desks.contains(active_desk))

    return render_template('desk.html', webtitle = "{} (My Active Desk)".format(active_desk.deskname), daynight = eval_time(), active_desk = active_desk, desk_notebooks = desk_notebooks)

@desks.route('/choose', methods=['GET', 'POST'])
@login_required
def choose_desk():
    all_desks = Desks.query.filter_by(owner = current_user.id)
    form = add_desk_form()
    if form.validate_on_submit():
        new_desk = Desks(deskname = form.deskname.data, desc = form.desc.data, owner = current_user.id)
        db.session.add(new_desk)
        db.session.commit()
        this_user = Users.query.get(current_user.id)
        this_user.active_desk = new_desk.id
        db.session.commit()
        flash("The new desk has been created! I've gone ahead and switched you over by making it your active desk! If you don't want that, activate a different desk below.")
        return redirect(url_for('desks.choose_desk'))
    else:
        for field, error in form.errors.items():
            flash('{} ({} error)'.format(error[0], field))

    return render_template('choosedesk.html', webtitle = "Switch Desk", daynight = eval_time(), all_desks = all_desks, form = form)

@desks.route('/activate')
@login_required
def activate_desk():
    if request.args.get('selection') is None:
        flash('You did not select a desk to activate, please try again.')
        return redirect(url_for('desks.choose_desk'))
    else:
        selection = int(request.args.get('selection'))
        this_user = Users.query.get(current_user.id)
        this_user.active_desk = selection
        db.session.commit()
        flash("You've been switched to your selected desk!")
        return redirect(url_for('desks.index'))

@desks.route('/manage', methods=['GET', 'POST'])
@login_required
def manage_desk():
    if request.args.get('selection') is None:
        flash('You did not select a desk to manage, please try again.')
        return redirect(url_for('desks.choose_desk'))
    else:
        selection = int(request.args.get('selection'))
        target_desk = Desks.query.get(selection)
        active_desk = Desks.query.get(current_user.active_desk)
        desk_notebooks = Notebooks.query.filter(Notebooks.associated_desks.contains(target_desk))
        form = edit_desk_form(obj = target_desk)
        if form.validate_on_submit():
            target_desk.deskname = form.deskname.data
            target_desk.desc = form.desc.data
            db.session.commit()
            flash("'{}' has been editted.".format(target_desk.deskname))
            return redirect(url_for('desks.choose_desk'))
        else:
            for field, error in form.errors.items():
                flash('{} ({} error)'.format(error[0], field))
        return render_template('managedesk.html', webtitle = "Manage My Desk", daynight = eval_time(), form = form, desk_notebooks = desk_notebooks, desk_id = target_desk.id)

@desks.route('/delete')
@login_required
def delete_desk():
    if request.args.get('selection') is None:
        flash('You did not select a desk to delete, please try again.')
        return redirect(url_for('desks.choose_desk'))
    else:
        if Desks.query.filter_by(owner = current_user.id).count() != 1:

            selection = int(request.args.get('selection'))
            target_desk = Desks.query.get(selection)

            if current_user.id == target_desk.owner:
                if current_user.active_desk == target_desk.id:
                    flash("You deleted your current active desk. I went ahead and switched you to your next available desk. We all need somewhere to sit at!")
                target_desk.notebooks = []
                db.session.delete(target_desk)
                this_user = Users.query.get(current_user.id)
                this_user.active_desk = Desks.query.filter_by(owner = current_user.id).first().id
                db.session.commit()
                flash("The selected desk has been deleted.")
            else:
                flash("Sorry but you can't delete someone else's desk.")

            return redirect(url_for('desks.choose_desk'))
        else:
            flash('You cannot delete your last desk, where will you sit at?')
            return redirect(url_for('desks.choose_desk'))

project/desks/templates/desks/choosedesk.html
{% extends 'max-1000.html' %}

{% block mainContent %}
  <h1>Choose a Desk</h1>
  <a href="{{ url_for('desks.index') }}" class="cancel_button">Return to Active Desk</a>
  {% for desk in all_desks %}
    <div class="linedBlock">
      <h2>{{ desk.deskname }}</h2>
      <p>{{ desk.desc }}</p>
      {% if desk.id == current_user.active_desk %}
        Current Active Desk
        {% else %}
        <a href="{{ url_for('desks.activate_desk', selection=desk.id) }}">Activate</a>
      {% endif %}
      | <a href="{{ url_for('desks.manage_desk', selection=desk.id) }}">Manage</a> | <a onClick="return confirm('Are you sure you want to delete this desk? Your notebooks will remain safe.');" href="{{ url_for('desks.delete_desk', selection=desk.id) }}">Delete</a>
    </div>
  {% endfor %}
  <div class="linedBlock">
    <h2>Notebook Shelf</h2>
    <p>Not a desk, but you can see all your notebooks here.</p>
    <a href="{{ url_for('notebooks.show_all') }}">See All Notebooks</a>
  </div>

  <h2>Add New Desk</h2>
  <div class="linedBlock">
    <form method="post">
      {{ form.hidden_tag() }}
      {{ form.deskname.label }}{{ form.deskname() }}
      {{ form.desc.label }}{{ form.desc() }}
      {{ form.submit(class_="redButton") }}
    </form>
  </div>
{% endblock %}

project/desks/templates/desks/desk.html
{% extends 'unconfined.html' %}

{% block mainContent %}
  <section class="confined-1000 linedBlock">
    <h1>{{ active_desk.deskname }}</h1>
    <p>Your desk contains all the current notebooks that you're working on. You can shift to a new desk if it's getting a little cluttered, but your old desk will be here waiting for you, exactly the way you left it!</p>
    <p><b>Tip:</b> You can use different desks for different subjects, and notebooks can exist on more than one desk at a time (unlike in real life). It's like folders but with more visual!</p>
    <p><a href="{{ url_for('desks.choose_desk')}}">Switch Desk</a> or <a href="{{ url_for('desks.manage_desk', selection=current_user.active_desk)}}">Manage This Desk</a></p>
  </section>

  <section class="centered">
    <h2>Notebooks on {{ active_desk.deskname }}</h2>

    <a href="{{ url_for('notebooks.add_notebook')}}"><div class="notebook_add">
      <div class="add_button"></div>
      <div class="add_text"></div>
    </div></a>

    {% for notebook in desk_notebooks %}
      <a href="{{ url_for('pages.show', notebook_id = notebook.id)}}"><div class="notebook_thumbnail" style="background-image: url({{notebook.cover_img}});">
        <div class="notebook_desc">
          {{ notebook.title }}
          <div class="notebook_author">by {{ notebook.associated_user.username }}</div>
        </div>
      </div></a>
    {% endfor %}
  </section>

  <section class="centered">
    <a href="{{ url_for('notebooks.show_all')}}">Show All Notebooks</a>
  </section>

{% endblock %}

project/desks/templates/desks/managedesk.html
{% extends 'max-1000.html' %}

{% block mainContent %}
  <h1>Manage Desk</h1>
  <p>You can rename your desk, change the description, or remove notebooks here.</p>
  <div class="linedBlock">
    <h2>Edit Details</h2>
    <form method="post">
      {{ form.hidden_tag() }}
      {{ form.deskname.label }}{{ form.deskname() }}
      {{ form.desc.label }}{{ form.desc() }}
      {{ form.submit(class_="redButton") }}
    </form>
    {% if request.headers.get('Referer') != None %}
      <a href="{{ request.headers.get('Referer') }}" class="cancel_button">Cancel</a>
    {% else %}
      <a href="{{ url_for('desks.choose_desk') }}" class="cancel_button">Back to Manage Desks</a>
    {% endif %}
  </div>

  <div class="linedBlock">
    <h2>Delete Desk</h2>
    <p>This action is irreversible! Deleting this desk will not delete the notebooks on the desk.</p>
    <a onClick="return confirm('Are you sure you want to delete this desk? Your notebooks will remain safe.');" href="{{ url_for('desks.delete_desk', selection=desk_id) }}" class="naviLink">Yes, Delete This Desk</a>
  </div>

  <div class="linedBlock">
    <h2>Remove Notebooks</h2>
    <ul>
      {% for notebook in desk_notebooks %}
      <li><a href="{{url_for('notebooks.remove_notebook', notebook_id=notebook.id, desk_id=desk_id)}}">{{notebook.title}}</a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}